name: doon
description: doon
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.3
  fluttertoast: ^8.2.2
  flutter_image_compress: ^2.0.4
  flutter_keyboard_visibility: ^5.4.0
  flutter_riverpod: ^2.4.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  package_info_plus: ^4.1.0
  path_provider: ^2.0.11
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
